Feature: Grundrechenarten
Generated by Yest

Background: Init Grundrechenarten


Scenario Outline:Addieren-Success

When ich drücke Taste "<IntA>"
 And ich drücke Taste "+"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 13      	| 5   	| 8   	|
	| 11      	| 6   	| 5   	|


Scenario Outline:Dividieren-Error

When ich drücke Taste "<IntA>"
 And ich drücke Taste "/"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 2       	| 8   	| 4   	|
	| 2       	| 4   	| 2   	|


Scenario Outline:Dividieren-Success

When ich drücke Taste "<IntA>"
 And ich drücke Taste "/"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 2       	| 8   	| 4   	|
	| 2       	| 4   	| 2   	|


Scenario Outline:Multiplizieren-Success

When ich drücke Taste "<IntA>"
 And ich drücke Taste "*"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 18      	| 3   	| 6   	|
	| 7       	| 1   	| 7   	|
	| 12      	| 4   	| 3   	|
	| 63      	| 7   	| 9   	|
	| 0       	| 5   	| 0   	|


Scenario Outline:Subtrahieren-Success

When ich drücke Taste "<IntA>"
 And ich drücke Taste "-"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 7       	| 9   	| 2   	|
	| 1       	| 2   	| 1   	|
	| -2      	| 7   	| 9   	|


