Feature: Grundrechenarten
Generated by Yest

Background: Init Grundrechenarten


Scenario Outline:Addieren-notZero-Success

When ich drücke Taste "<IntA>"
 And ich drücke Taste "+"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 12      	| 8   	| 4   	|


Scenario Outline:Addieren-zero-Success

When ich drücke Taste "<IntA>"
 And ich drücke Taste "+"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 5       	| 5   	| 0   	|


Scenario Outline:Dividieren-notZero-Success

When ich drücke Taste "<IntA>"
 And ich drücke Taste "/"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 2       	| 8   	| 4   	|


Scenario Outline:Dividieren-zero-Error

When ich drücke Taste "<IntA>"
 And ich drücke Taste "/"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| Infinity	| 4   	| 0   	|


Scenario Outline:Multiplizieren-notZero-Success

When ich drücke Taste "<IntA>"
 And ich drücke Taste "*"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 12      	| 2   	| 6   	|
	| 15      	| 5   	| 3   	|
	| 36      	| 4   	| 9   	|


Scenario Outline:Multiplizieren-zero-Success

When ich drücke Taste "<IntA>"
 And ich drücke Taste "*"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 0       	| 5   	| 0   	|


Scenario Outline:Subtrahieren-notZero-Success

When ich drücke Taste "<IntA>"
 And ich drücke Taste "-"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 5       	| 10  	| 5   	|


Scenario Outline:Subtrahieren-zero-Success

When ich drücke Taste "<IntA>"
 And ich drücke Taste "-"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 8       	| 8   	| 0   	|


