Feature: Grundrechenarten
Generated by Yest

Background: Init Grundrechenarten


Scenario Outline:Addieren-Success

When ich drücke Taste "<IntA>"
 And ich drücke Taste "+"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 5       	| 5   	| 0   	|


Scenario Outline:Addieren-Success1

When ich drücke Taste "<IntA>"
 And ich drücke Taste "+"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 12      	| 8   	| 4   	|


Scenario Outline:Dividieren-Error

When ich drücke Taste "<IntA>"
 And ich drücke Taste "/"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| Infinity	| 4   	| 0   	|


Scenario Outline:Dividieren-Success

When ich drücke Taste "<IntA>"
 And ich drücke Taste "/"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 2       	| 8   	| 4   	|


Scenario Outline:Multiplizieren-Success

When ich drücke Taste "<IntA>"
 And ich drücke Taste "*"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 0       	| 5   	| 0   	|


Scenario Outline:Multiplizieren-Success1

When ich drücke Taste "<IntA>"
 And ich drücke Taste "*"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 12      	| 2   	| 6   	|
	| 36      	| 4   	| 9   	|


Scenario Outline:Subtrahieren-Success

When ich drücke Taste "<IntA>"
 And ich drücke Taste "-"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 2       	| 5   	| 3   	|


Scenario Outline:Subtrahieren-Success1

When ich drücke Taste "<IntA>"
 And ich drücke Taste "-"
 And ich drücke Taste "<IntB>"
Then ich prüfe ob das Ergebnis "<Ergebnis>" ist

Examples: 
	| Ergebnis	| IntA	| IntB	|
	| 8       	| 8   	| 0   	|


